blank_issues_enabled: false
contact_links:
  - name: Contribution guide
    url: https://github.com/dantejvar28/widdgyy/blob/main/CONTRIBUTING.md
    about: Please read the contribution workflow before opening an issue.
